### ISSUE TITLE
$sudo service tftpd-ha restart 少一个字母p

### ISSUE THREAD

**Issue by wicgee** [tsaiyuyan/blog-comments#104]
[Ubuntu 安裝 TFTP Server ](https://tsaiyuyan.github.io/2020/05/19/ubuntu-an-zhuang-tftp-server/)

这篇文章命令：sudo service tftpd-ha restart
 少了一字母P，正确的是：`sudo service tftpd-hpa restart`

**Comment by tsaiyuyan** [comment]
已修正 感謝回饋
